SAP: Make tox -e pep8 work again
It failed to install the dependencies even with a pinned setuptools<45
in the upper constraints:

      File "/tmp/pip-install-jx7q3ls5/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'

The problem is, that a newer versions of `virtualenv` also pull in a new
version of setuptools. I haven't found a way to constrain the setuptools
version used by tox's creation of a virtualenv. Therefore, we now limit
the virtualenv version, which should bring us back to supported
territory.