Fix test env by pinning bandit <1.6
We run into failures when installing the virtualenv for testing, because
newer bandit versions don't support Python 2.7 anymore. Pinning it to a
supported version fixes this.

  ERROR: Package 'bandit' requires a different Python: 2.7.18 not in '>=3.5'

Picked from sapcc/nova/commit/232140371d753a9173abdc324fb10c56b0430980